// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxgS4UMXGtOx04EGV30cWt0h-bR2_vgyc',
    appId: '1:488679099792:web:57ad1b70369af7582d7715',
    messagingSenderId: '488679099792',
    projectId: 'fitme-app-55303',
    authDomain: 'fitme-app-55303.firebaseapp.com',
    storageBucket: 'fitme-app-55303.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB05oN8mViOqSBH8az7ZQXF9MXfYCy9iP8',
    appId: '1:488679099792:android:45318aca0192dc8b2d7715',
    messagingSenderId: '488679099792',
    projectId: 'fitme-app-55303',
    storageBucket: 'fitme-app-55303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA8KosbksSSO-Dx8XCZAk_Ji4zWMX5vYs',
    appId: '1:488679099792:ios:078780dd56246a482d7715',
    messagingSenderId: '488679099792',
    projectId: 'fitme-app-55303',
    storageBucket: 'fitme-app-55303.appspot.com',
    androidClientId: '488679099792-0pg3tsq7bgvph1nuh1iamo5tb9fssdv3.apps.googleusercontent.com',
    iosClientId: '488679099792-qfosotq9anbfm95fklv9sff8n6r9lb5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealPlan',
  );
}
